os: linux
dist: bionic
language: php

php:
  - 7.3
  - 7.4
  - master
  - nightly

env:
  global:
    - CC_TEST_REPORTER_ID=9d5a0a0dc82513776f7a233a9175d4107966a67c8dd80a6fc86179f93d6dca25

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^analysis-.*$/

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr12 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
