name: normalize composer.json

on:
  push:
    paths:
      - "composer.json"
      - "composer.lock"

jobs:
  normalize:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Validate Composer configuration
        run: composer validate --strict

      - name: Normalize composer.json
        uses: "docker://ergebnis/composer-normalize-action:latest"
        with:
          args: "--indent-style=space --indent-size=4 --no-update-lock --ansi"

      - name: Update composer.json
        uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: normalize composer.json
