name: Check & fix styling

on:
  push:
    paths:
      - "**.php"
      - ".php-cs-fixer.php"

jobs:
  style:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important!

      - name: Fix style
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --allow-risky=yes

      - uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: Fix styling
