name: PHPunit Tests

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: ["8.0", "7.4"]
        dependency-version: ["prefer-lowest", "prefer-stable"]
        os: ["ubuntu-latest", "windows-latest"]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
        restore-keys: |
          dependencies-php-${{ matrix.php }}-composer-
          dependencies-php-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: json, dom, curl, libxml, mbstring
        coverage: none

    - name: Install dependencies
      run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

    - name: Execute tests
      run: vendor/bin/phpunit
