name: PHPunit Tests

on: ["push", "pull_request"]

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: ["8.0", "8.1"]
        dependency-version: ["prefer-lowest", "prefer-stable"]
        laravel: [9.*, 8.*]
        os: ["ubuntu-latest", "windows-latest"]
        include:
          - laravel: 9.*
            testbench: ^7.0
          - laravel: 8.*
            testbench: ^6.24

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-L${{ matrix.laravel }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            dependencies-php-${{ matrix.php }}-composer-L${{ matrix.laravel }}
            dependencies-php-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, fileinfo
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               export XDEBUG_MODE=coverage
          elif [ "$RUNNER_OS" == "Windows" ]; then
               set XDEBUG_MODE=coverage
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
          vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
        shell: bash

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: run-${{ matrix.os }}-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ matrix.laravel }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v

      - name: Upload to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v1
        with:
          files: ./build/logs/clover.xml # optional
          flags: unittests # optional
          name: run-${{ matrix.os }}-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ matrix.laravel }}

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
